### PR TITLE
ironstrings: increase stack size

### LINKED ISSUE #127: ironstrings alloca_probe stack size calculation errors
Hello!

I have a function at 0x1802b4d40 in this file
[sample.txt](https://github.com/mandiant/flare-ida/files/14120913/sample.txt) (ignore extension its a dll, github wouldnt upload otherwise)

```
text:00000001802B4D40 000                 mov     [rsp-8+arg_0], rbx
.text:00000001802B4D45 000                 push    rbp
.text:00000001802B4D46 008                 push    rsi
.text:00000001802B4D47 010                 push    rdi
.text:00000001802B4D48 018                 push    r12
.text:00000001802B4D4A 020                 push    r13
.text:00000001802B4D4C 028                 push    r14
.text:00000001802B4D4E 030                 push    r15
.text:00000001802B4D50 038                 lea     rbp, [rsp-0F00h]
.text:00000001802B4D58 038                 mov     eax, 1000h
.text:00000001802B4D5D 038                 call    __alloca_probe
.text:00000001802B4D62 1038                sub     rsp, rax
.text:00000001802B4D65 1038                mov     rdi, r8
.text:00000001802B4D68 1038                mov     r14, rdx
.text:00000001802B4D6B 1038                mov     r15, rcx
.text:00000001802B4D6E 1038                xor     esi, esi
```

It seems like alloca_probe is messing with the stack size calculations, I also have another function where it did this, it specially happens on functions with large stacks. Do you have a clue hjow to fix it? I tried but couldnt figure it out.

Here's the program output:

[ironstrings2.log](https://github.com/mandiant/flare-ida/files/14120980/ironstrings2.log)

### PR DESCRIPTION
**Pull request by mr-tz**
partly addresses #127

@llebout, can you test this fix on your side as well please?

### CODE REVIEW

**Comment by llebout** [comment]
@mr-tz On it

**Comment by llebout** [comment]
@mr-tz 

The patch does seem to help for one function I think (though it may already have worked that way before too, or on some other versions of the sample I have).

0x1802b4d40 - It may have worked this way before too, found 3 strings while in manual analysis I was able to find much more. It seems like the emulator gets stuck on a condition or something and cannot reach all the code paths of the function.
What ironstrings with patch gave:
```
0x1802B4D40        0x1802B4FE0        0xD50              Function Pal.PalBuildObject.OnBeginInteractBuilding
0x1802B4D40        0x1802B523B        0xDD0              Function Pal.PalNetworkItemComponent.RequestDrop_ToServer
0x1802B4D40        0x1802B5536        0xD90              Function Pal.PalCharacterParameterComponent.OnDamage
```
Manual analysis string recovery results using a debugger and stepping through:
```
0x1802b4d40
"Function Pal.PalBuildObject.OnBeginInteractBuilding"
"Function Pal.PalNetworkItemComponent.RequestDrop_ToServer"
"Function Pal.PalCharacterParameterComponent.OnDamage"
"Function WBP_PalNPCHPGauge.WBP_PalNPCHPGauge_C.OnTakeDamage"
"Function Pal.PalPlayerState.SendDamage_ToServer"
"Function Pal.PalPlayerController.OnDamage"
"Function WBP_PlayerUI.WBP_PlayerUI_C.OnPlayerDamage"
"Function BP_MonsterBase.BP_MonsterBase_C.OnInflictDamage"
"Function Pal.PalDamageReactionComponent.ApplyDamageForHP"
"Function Pal.PalCharacterParameterComponent.OnDamage"
"Function Pal.PalDamageReactionComponent.ApplyDamageForHP"
"Function Pal.PalPlayerCharacter.IsGuildMaster"
"Function Pal.PalUIGuildMenu.IsAdminLocalPlayer"
"Function Pal.PalMapObjectDeathDroppedCharacterModel.IsSameGuildInLocalPlayer"
"Function Pal.PalMapObjectDeathPenaltyStorageModel.IsSameGuildInLocalPlayer"
"Function Pal.PalLocationPointBaseCamp.IsSameGuildWithPlayer"
"IsDying"
".OnPullTrigger"
"Function WBP_Map_Base.WBP_Map_Base_C.SetupLocationPointIcon"
"Function Pal.PalPlayerState.EnterChat_Receive"
"Function WBP_PalHUD_InGame_InputListener.WBP_PalHUD_InGame_InputListener_C.OpenChat"
"Function Pal.PalNetworkIndividualComponent.AddPlayerCharacterStatusPoint_ToServer"
"BP_SkillEffect"
"broadcast"
```
0x180138aa0 - Did not work at all like before, shows this recursion error
ironstrings-issue
, and increasing Python stack size with `sys.setrecursionlimit(5000)` or higher lets it run for longer but it still cannot discover paths to targets, see log file for debug log.
0x1802ae880 - Did not recover any strings, I know there is numerous strings from manual analysis, one of which is `TreasureBox_C`

Debug log file, contains a run on single function mode for all three previously problematic functions
[ironstrings-issue.log](https://github.com/mandiant/flare-ida/files/14185798/ironstrings-issue.log)

Overall I think this patch gave mixed results, and the strings that were recovered after the patch I think could already be recovered before and no new strings were discovered.

Thanks a lot for working on this.

**Comment by mr-tz** [comment]
Hm, my guess is that not all paths for `0x1802b4d40` are explored correctly in flare-emu (more time would be needed to confirm). The same goes for `0x1802ae880` which has many blocks and paths.
To fix this, I think a closer look at flare-emu's `iterateAllPaths` and `getPathsToTarget` functions would be good next steps.

`0x180138aa0` is massive (my IDA even complains about to many lines and the function stack is huge as well), so I think it's out of scope for the current usage of ironstrings.

FWIW with the fix here I get the 3 strings you mention above vs. 0 before.

**Comment by mr-tz** [comment]
merging this as a small improvement, but it's a not a complete fix

**Pull request merged**
